###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Curso do Zero a Programador",
    "price": 959.59
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Consultoria de engenharia de software",
    "price": 1459.59
}